### ISSUE TITLE
Roary not using packaged executables

### ISSUE THREAD

**Issue by bachev** [sanger-pathogens/Roary#215]
Hi there,

maybe this is due to preliminary status of Roary.

### Bug report
The prepackaged download .tar.gz file on http://sanger-pathogens.github.io/Roary/ apparently comes with binaries for Linux and OSX. However, if the user does not actively take them up in the $PATH, Roary will not use them (and fail if there are no other versions of them in the $PATH).

#### Suggested resolution
Test whether a tool is in the current PATH (see #214) and if not, make sure the prepackaged version is used.

**Comment by andrewjpage** [comment]
Good spot! 

The recommended installation method for the dependancies is using homebrew/linuxbrew, apt or from source. 
I dont document that these binaries are available anymore (because as you point out in your other issue, they are a pain) but they have solved the odd installation issue in the past when other methods have failed.  In the past I checked and used these bundled dependancies after the installed ones,  but it proved to be unreliable in practice.

I would be leaning towards deleting them entirely to avoid confusion.
Andrew
