### ISSUE TITLE
Error message: Cannot find the mcxdeblast executable, please ensure its in your PATH

### ISSUE THREAD

**Issue by rasmusmarvig** [sanger-pathogens/Roary#217]
Dear all

I get the following error message when running Roary:
"Cannot find the mcxdeblast executable, please ensure its in your PATH"

When I run "roary -a" everything looks fine:
"
2015/12/16 21:12:07 Looking for 'Rscript' - found /usr/bin/Rscript
2015/12/16 21:12:07 Determined Rscript version is 3.1
2015/12/16 21:12:07 Looking for 'awk' - found /bin/awk
2015/12/16 21:12:07 Looking for 'bedtools' - found /usr/bin/bedtools
Use of uninitialized value in concatenation (.) or string at /usr/local/share/perl5/Bio/Roary/External/CheckTools.pm line 129.
2015/12/16 21:12:07 Determined bedtools version is 
Use of uninitialized value in numeric lt (<) at /usr/local/share/perl5/Bio/Roary/External/CheckTools.pm line 130.
2015/12/16 21:12:07 Roary needs bedtools 2.1 or higher. Please upgrade and try again.
2015/12/16 21:12:07 Looking for 'blastp' - found /home/rlmn/ncbi-blast-2.2.30+/bin/blastp
2015/12/16 21:12:07 Determined blastp version is 2.2.30
2015/12/16 21:12:07 Looking for 'grep' - found /bin/grep
2015/12/16 21:12:07 Optional tool 'kraken' not found in your $PATH
2015/12/16 21:12:07 Optional tool 'kraken-report' not found in your $PATH
2015/12/16 21:12:07 Looking for 'mafft' - found /usr/local/bin/mafft
2015/12/16 21:12:07 Determined mafft version is 7.267
2015/12/16 21:12:07 Looking for 'makeblastdb' - found /home/rlmn/ncbi-blast-2.2.30+/bin/makeblastdb
2015/12/16 21:12:07 Determined makeblastdb version is 2.2.30
2015/12/16 21:12:07 Looking for 'mcl' - found /usr/local/bin/mcl
2015/12/16 21:12:07 Determined mcl version is 14-137
2015/12/16 21:12:07 Looking for 'parallel' - found /home/rlmn/bin/parallel
2015/12/16 21:12:07 Determined parallel version is 20141122
2015/12/16 21:12:07 Looking for 'prank' - found /home/rlmn/prank/bin/prank
2015/12/16 21:12:07 Looking for 'sed' - found /bin/sed
2015/12/16 21:12:07 Looking for 'cd-hit' - found /home/rlmn/cd-hit-v4.6.1-2012-08-27/cd-hit
2015/12/16 21:12:07 Determined cd-hit version is 4.6
2015/12/16 21:12:07 Required tool missing. Can't find one of fasttree/FastTree in your $PATH.
2015/12/16 21:12:07 Roary version 3.5.6
2015/12/16 21:12:07 Error: You need to provide at least 2 files to build a pan genome
"

I have already installed latest version of mcl package (14-13; same as used in the installation documentation); however, no mcxdeblast executable is generated. I get no error messages, so I it seems to me that mcxdeblast is not in the standard mcl package. I have also tried to install mcl version 10-148 to see if an older version would contain mcxdeblast.
I downloaded mcl from: http://micans.org/mcl/ 

Thanks.

**Comment by andrewjpage** [comment]
Hi,
Thanks for trying out Roary. Hopefully we'll get it sorted quickly.

What operating system and version are you using?  The easiest way to install the dependancies is to use homebrew (osx), linuxbrew (linux) or apt (ubuntu).  If your installing the dependancies manually, its a bit of a pain I'm afraid, which is why I recommend using the methods just mentioned, although I do appreciate that its not possible for everyone.

In the mcl download, the mcxdeblast script is in ./src/alien/oxygen/src/mcxdeblast
After you have done ' ./configure && make ' you need to add xxxx/src/alien/oxygen/src to your PATH.
FastTree also appears to be missing. The (install_dependancies.sh)[https://github.com/sanger-pathogens/Roary/blob/master/install_dependencies.sh] script builds all the dependancies from source (so that it will work on TravisCI, which is Ubuntu 12.04), which might help if you are comfortable with reading BASH scripts.

Andrew

**Comment by rasmusmarvig** [comment]
Dear Andrew,

Thanks, your help solved my problem.
I needed to /src/alien/oxygen/src to my path (and also installed FastTree), and roary runs smoothly.

The reason that i did not use brew is that I got the following error and therefore found it easier to pursue a strategy installing dependencies myself:
rlmn@node1:>brew install mcl
==> Installing mcl from homebrew/homebrew-science
Error: homebrew/science/mcl cannot be built with any available compilers.
To install this formula, you may need to:
  brew install gcc
rlmn@node1:>brew install gcc
==> Installing dependencies for gcc: zlib, xz, gmp, mpfr, libmpc, isl
==> Installing gcc dependency: zlib
Error: zlib cannot be built with any available compilers.
To install this formula, you may need to:
  brew install gcc
rlmn@node1:>brew install zlib
Error: zlib cannot be built with any available compilers.
To install this formula, you may need to:
  brew install gcc

Best of regards from a research camp in Uruguay. Sitting here with greetings from Gregorio Bentancor who motivated to try out Roary.

Rasmus.

**Comment by andrewjpage** [comment]
Hi Rasmus,
Great to hear you got it working, and it seems to be a very small world indeed!  

That error with brew and gcc it a funny chicken and egg problem!   To solve it you install gcc with your own packaging system (most likely there already) and then link it so that brew can use it. So if you had version 4.8 of gcc you would do:

ln -s $(which gcc) ~/.linuxbrew/bin/gcc-4.8
ln -s $(which g++) ~/.linuxbrew/bin/g++-4.8
ln -s $(which gfortran) ~/.linuxbrew/bin/gfortran-4.8

where '.linuxbrew' is the directory where you installed linuxbrew.  Then brew should work.

Andrew

**Comment by mworkentine** [comment]
Quick note for others who run across this: If you are installing mcl on your own you can add the `--enable-blast` option to the configure script to get the mcxdeblast exectuable.  See the mcl homebrew formula for an example.

**Comment by andrewjpage** [comment]
Thanks for the tip
