### ISSUE TITLE
multi fasta file for each core gene

### ISSUE THREAD

**Issue by rndg20** [sanger-pathogens/Roary#252]
Is there a way to create a multifasta file, showing the nucleotide alignment of all isolates, for each core gene? 

I've tried this method, by selecting 1 gene;
query_pan_genome ­a gene_multifasta ­g clustered_proteins ­n gryA,mecA,abc *.gff
However, this only provides the amino acid sequence. Is there a way in which I can get the nucleotide sequences of all the isolates for that particular gene? 

Also can I apply this for all of the core genes? Is there an easier way than listing them individually?

**Comment by andrewjpage** [comment]
Yes. Run roary with the following parameters:

roary -e -n -z *.gff

You will then have a directory called pan_genome_sequences which contains a
single multifasta alignment for each gene in all isolates.

The '-e -n' parameters perform the alignment of the genes, and '-z' means
keep the intermediate files rather than deleting them.
Andrew
