### ISSUE TITLE
Is it possible to build a pan-genome tree using Roary

### ISSUE THREAD

**Issue by raymondkiu** [sanger-pathogens/Roary#253]
Hello

I have generated a core-genome tree using protein clusters, however, is it possible to generate a pan-genome tree using Roary based on both core and accessory genome protein clusters?

**Comment by MathGon** [comment]
Have you finally managed to build it?

**Comment by raymondkiu** [comment]
Not yet. I am still looking to build a pan-genome tree.

**Comment by andrewjpage** [comment]
Hi,
You can vary the core definition (-cd) to include more of the accessory genes in the final multifasta alignment (for building a tree).  However you would want to be very careful about this since the accessory genome usually contains MGEs, and including these in a tree may/will give you erroneous results.  In virtually every dataset I've encountered, including the entire accessory would be a very bad idea.
