### ISSUE TITLE
paralogs not being split

### ISSUE THREAD

**Issue by SWittouck** [sanger-pathogens/Roary#290]
Hi,

I have some quick questions about paralog splitting in roary:
- When running roary with split paralogs enabled (default option), I noticed that not all gene groups with paralogs get split. This seems to be the case when the gene neighbourhood of two paralogs is too similar (i.e. they are neighbours). Is this correct? 
- The gene groups that still contain paralogs, are they included in the core genome alignment? If yes, how does roary decide which of the paralogous sequences to include? 

Thanks in advance.

**Comment by andrewjpage** [comment]
Hi,
When splitting paralogs, its a best effort. When you have multiple insertions of the same gene into the same place, generally bioinformatics becomes painful (particularly when using short reads), as you have observed.  It is difficult to split out the paralogs in this instance, so Roary is conservative in this situation, and doesn't split.

Clusters which contain paralogs are not included in the core genome alignment.  So in the spreadsheet of gene presence and absence, the column 'Avg sequences per isolate' must equal 1, and the number of isolates in the cluster must meet the threshold for the core definition percentage (core = in 99% of isolates by default). If you've found otherwise, then its a bug.
Andrew

**Comment by SWittouck** [comment]
Hi Andrew,

Thank you for the quick and clear answer.

Stijn
