### ISSUE TITLE
could not determine version of cd-hit

### ISSUE THREAD

**Issue by hattiechung** [sanger-pathogens/Roary#322]
Hello, 

**_I'm new to roary. I tried running a basic command with 9 genomes, "roary *gff", returning the following error:_** 
sh: line 1: 90488 Trace/BPT trap: 5       /usr/local/bin/cd-hit -i _combined_files -o _clustered -T 1 -M 1800 -g 1 -s 1 -d 256 -c 1 > /dev/null 2>&1
Cant open file: _clustered.clstr
------------- EXCEPTION: Bio::Root::Exception -------------
MSG: Could not read file '_clustered': No such file or directory
STACK: Error::throw
STACK: Bio::Root::Root::throw /Library/Perl/5.18/Bio/Root/Root.pm:447
STACK: Bio::Root::IO::_initialize_io /Library/Perl/5.18/Bio/Root/IO.pm:268
STACK: Bio::SeqIO::_initialize /Library/Perl/5.18/Bio/SeqIO.pm:513
STACK: Bio::SeqIO::fasta::_initialize /Library/Perl/5.18/Bio/SeqIO/fasta.pm:87
STACK: Bio::SeqIO::new /Library/Perl/5.18/Bio/SeqIO.pm:389
STACK: Bio::SeqIO::new /Library/Perl/5.18/Bio/SeqIO.pm:435
STACK: Bio::Roary::ChunkFastaFile::_input_seqio /Library/Perl/5.18/Bio/Roary/ChunkFastaFile.pm:27
STACK: Bio::Roary::ChunkFastaFile::sequence_file_names /Library/Perl/5.18/Bio/Roary/ChunkFastaFile.pm:48
STACK: Bio::Roary::ParallelAllAgainstAllBlast::_sequence_file_names /Library/Perl/5.18/Bio/Roary/ParallelAllAgainstAllBlast.pm:61
STACK: Bio::Roary::ParallelAllAgainstAllBlast::run /Library/Perl/5.18/Bio/Roary/ParallelAllAgainstAllBlast.pm:112
STACK: Bio::Roary::run /Library/Perl/5.18/Bio/Roary.pm:92
STACK: Bio::Roary::CommandLine::Roary::run /Library/Perl/5.18/Bio/Roary/CommandLine/Roary.pm:297
STACK: /usr/local/bin/roary:14

**Typing "roary -a" gives an output, including the following, showing that the version of cd-hit cannot be determined:** 

2017/04/14 23:48:42 Looking for 'cd-hit' - found /usr/local/bin/cd-hit
dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/6/libgomp.1.dylib
  Referenced from: /usr/local/bin/cd-hit
  Reason: image not found
2017/04/14 23:48:42 Could not determine version of cd-hit - please install version 4.6 or higher
2017/04/14 23:48:42 Looking for 'FastTree' - found /usr/local/bin/FastTree
Use of uninitialized value in concatenation (.) or string at /Library/Perl/5.18/Bio/Roary/External/CheckTools.pm line 129.
2017/04/14 23:48:43 Determined FastTree version is 
2017/04/14 23:48:43 Roary version 3.8.0

**However, cd-hit is installed in /usr/local/bin/cd-hit. For good measure, I tried installing again with brew via "brew install cd-hit", reaffirming that I do have cd-hit 4.6.6:** 
Warning: homebrew/science/cd-hit-4.6.6 already installed

**I saw a different thread suggesting that gcc needs to be updated. But I think I do have the latest version of gcc, via "gcc --version":** 
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix

**Perhaps I am missing some key path dependencies. Any help would be great. Thank you.**

**Comment by rawrnold** [comment]
I had the same problem. I assume that you are running this on a mac. The issue is due to the fact that cd-hit wants a gcc5 compiler, but macOSX only has gcc. And because cd-hit isn't working, roary fails. After several hours, I was able to come up with the following solution.

1. Install macports. https://www.macports.org/install.php
2. Update macports:
`sudo port selfupdate`
3. Install gcc5 using macports. This version of gcc is compatible with cd-hit.
`sudo port install gcc5`
This step takes some time. 
4. Install gcc_select using macports. This software lets you tell OSX which version of gcc to use
`port install gcc_select`
5. Use the following command to see the available versions on your computer
`port select --list gcc`
You should see mp-gcc5 as one of the options.
6. Now that everything is installed, you can set the active version of gcc to gcc5
`sudo port select --set gcc gcc5`
Your gcc version is now updated, but for whatever reason, the homebrew installed cd-hit does not work well with this work around. So...
7. Uninstall cd-hit with homebrew (if you already uninstalled it)
`brew uninstall cd-hit`
8. Download the latest version of cd-hit from https://github.com/weizhongli/cdhit
9. Unpack the zip in the directory of your choice (cd-hit scripts will be placed there)
10. Open terminal, and navigate to the cd-hit folder. I'm assuming it is in your home directory.
`cd ~/cdhit-master/`
11. Now, you can install cd-hit manually with the following command
`make`
12. If you did steps 1-6 correctly, then cd-hit should compile without issues.  If not you will receive an error about omp.h being missing. If this is the case, be sure to uninstall cd-hit with the command `make clean`
13. Assuming cd-hit installed correctly, you now need to add it to your path. I keep my path in a file called .profile. I edit it with the command
`nano ~/.profile`
14. In nano, type the following text:
`export PATH="~/cdhit-master:$PATH"`
Press ctrl+x to exit. It will ask if you want to save. Press `y` and then enter to accept the file name.
15. Finally, you need to re-initialize your profile with the command:
`. ~/.profile`
Doing this will activate the new path that you added.


You should now be able to use cd-hit. To test this run the command: `cd-hit`
If everything went correctly, you will see the program's help output. If not, it will fail to run.

With cd-hit up and running, you should now be able to run roary without any further issues.

**Comment by hattiechung** [comment]
Wow! Thank you @rawrnold for such a detailed response. I should've replied that since posting the question, I nuked a lot of dependencies on my computer and used conda to install roary. It works well now. But this is very useful for other packages that uses cd-hit so I will save this!

**Comment by rawrnold** [comment]
No worries. I spent the past 1.5 days trying to figure this out so that I could run roary. Unfortunately, cd-hit has almost no information in its README file, and there doesn't seem to be much support for mac-based issues. I just want to save people time when trying to get this software suite up and running.

**Comment by 4ureliek** [comment]
I ran into the same issue - thank you for this!!

**Comment by andrewjpage** [comment]
Which installation method did you use? Brew, conda, docker?

**Comment by 4ureliek** [comment]
I used brew - the issue is with the gcc install more than roary per say. So when I could not run it, I tried to use docker but got this error:
`Use of uninitialized value in require at /usr/lib/x86_64-linux-gnu/perl/5.26/Encode.pm line 61.`
And it was not running (probably some mistakes of my own in the command line since I had never used docker before) so I went back trying on my computer. Note that I also got this error (but line 60 - perl 5.16).

Note that when I installed roary with brew it broke prokka (probably similar gcc issue than the one with cd-hit). Prokka was running fine but as soon as I installed roary with brew I got these messages:
`[02:09:45] Looking for 'makeblastdb' - found /home/akapusta/.linuxbrew/bin/makeblastdb
makeblastdb: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory
[02:09:45] Could not determine version of makeblastdb - please install version 2.2 or higher
Warning: The post-install step did not complete successfully
You can try again using brew postinstall homebrew/science/prokka`

Cheers,
Aurelie

**Comment by tseemann** [comment]
@4ureliek that is **not** an error. it is a warning. and it's not in Roary. many of us get that warning. I have not managed to fully trace why it is happening. But you can safely use Roary still.

Your brew was probably broken. `brew doctor` is important to run.   Unfortunately it is easy to break brew . Best stratgey is to put it in `/home/linuxbrew/.linuxbrew` if possible

**Comment by bhanusakhamuri** [comment]
It was great help to me. I encountered with the same issue and the step by step procedure helped me fix the issue and was able to run Roary perfectly. Thanks So much.

**Comment by shodhak** [comment]
I was getting same error when used Roary with option "-r", but once i removed it from the command, the code works fine without any errors.
