### ISSUE TITLE
Sequences Missing in core_gene_alignment.aln file

### ISSUE THREAD

**Issue by fphage** [sanger-pathogens/Roary#347]
Installed ROARY on Biolinux 8
Roary installation checked using 
roary -a
Everything is looking fine
I ran the following command
roary -e -n --mafft -p 8 -t 1 -r -f foldername .*gff

After analysis 
There are no aligned sequences in the core_gene_alignment.aln file - It contains only the headers

Any  help

Thanks

**Comment by tseemann** [comment]
@fphage you'll leed to provide the output log file. maybe run it again with `roary -v YOUR_STUFF 2>&1 > roary.log`

**Comment by andrewjpage** [comment]
I noticed that you change the translation table to. 1. What type of
bacteria is it?

On 5 Sep 2017 4:41 pm, "fphage" <notifications@github.com> wrote:

Installed ROARY on Biolinux 8
Roary installation checked using roary -a
Everything is looking fine

I ran the following command
roary -e -n --mafft -p 8 -t 1 -r -f foldername

After analysis
There are sequences in the core_gene_alignment.aln file - It has only the
headers

Any help

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sanger-pathogens/Roary/issues/347>, or mute the thread

**Comment by fphage** [comment]
https://github.com/andrewjpage

My files belong to bacteriophages. In the ROARY user manual suggested translation table is 1 for viruses

**Comment by yanadya** [comment]
Bacteriophages are  quite diverse - I will not be surprised if  there are no core in your collection.   Try to  lower % of similarity.

**Comment by fphage** [comment]
@tseemann 
[summary_statistics.txt](https://github.com/sanger-pathogens/Roary/files/1287726/summary_statistics.txt)
Log file attached

**Comment by fphage** [comment]
[roary.log.txt](https://github.com/sanger-pathogens/Roary/files/1287729/roary.log.txt) 
Logfile

**Comment by fphage** [comment]
@yanadya 
I will try using lower %
The phage genomes i was using as input are highly identical.
