### ISSUE TITLE
"Jumps" of the number of conserved genes every 100 genomes

### ISSUE THREAD

**Issue by karchern** [sanger-pathogens/Roary#356]
Hi,

I'm sorry for the cryptic title, but I found no better way to describe this issue. I ran roary on a couple of hundred genomes annotated with prokka. The number of conserved genes plotted against the number of genomes has peculiar jumps at every 100ths, 200ths (and so on) genome. The "true" number of core genes is around 800, as reported in the summary file from roary. 

Check out the following link for a plot, which plots the number of conserved genes (colMeans of the number_of_conserved_genes.Rtab file) against the number of genomes.

[conserved_genes.pdf](https://github.com/sanger-pathogens/Roary/files/1348832/conserved_genes.pdf)

Anyone having any idea what's going on here? 
Cheers!

**Comment by andrewjpage** [comment]
This is expected behaviour.  By default a gene is counted as core if it is present in 99% or more isolates.  Using basic Math, when you have less than 100 samples, a gene is only counted as core if it is present in all samples, 100-200 samples, a gene is counted as core if it is present in all minus 1 samples etc...  

You can either set the core definition (-cd) to be 100%, but will get a small core due to noise like assembly errors, or use your favourite curve fitting algorithm in R to draw a different figure.

**Comment by andrewjpage** [comment]
I should also say that the jumps you are seeing in your data are very very extreme which may indicate a problem with the input files (e.g. poor assemblies).

**Comment by karchern** [comment]
That makes complete sense. Thanks for the quick answer. Could you elaborate more as to why poor assemblies can create more extreme jumps?

**Comment by andrewjpage** [comment]
garbage in = garbage out

A poor assembly will usually contain more fragmented genes and missassemblies. So the probability of a core gene cluster containing a fragmented gene will be increased. Thus you will get more extreme swings.

**Comment by karchern** [comment]
Thank you very much! This was very helpful. I'm closing this issue.
