### ISSUE TITLE
Paralog splitting in roary

### ISSUE THREAD

**Issue by karchern** [sanger-pathogens/Roary#357]
This is more a conceptual question regarding roary than an issue with the software, so please excuse me if this is not appropriate here:
How exactly does the paralog splitting work in roary? In the paper, it says that "conserved gene neighborhood" information is used to split paralog genes. Does that simply mean that if two similar genes are found on the same input sequence (contig), they are labeled paralogs and split? 

Have you ever rigorously estimated how good of a classifier roary is when it comes to classifying paralogoes events? If not, could you please give me your opinion on the matter? 

These questions are motivated as I don't understand why roary (apparently) splits orthologs into paralogs as described in Issue #355. 

Thank you!

**Comment by andrewjpage** [comment]
So technically we use the term paralog loosely and infact it could also be an ortholog, depending on the parameters the user provides.  We look for any cluster where there is more than 1 sequence from a single sample, then look at how 5 genes upstream and downstream have been clustered. This gives us a fingerprint for the syntany and we can often use it to split the cluster. It does have the effect that genes with identical sequences can end up in different clusters, but that's because they appear in distinct different parts of the underlying genome.  Splitting clusters isnt perfect, so if you have the same gene inserted over and over or flanked by multiple transposons it wont have enough information. Often this can manifest as a broken contig and is a fundamental limitation of short read sequencing technology.
