### ISSUE TITLE
unexpected output folder

### ISSUE THREAD

**Issue by thkuo** [sanger-pathogens/Roary#368]
I tried to include a command of roary in my shell script as well as a Snakefile:
```
roary -p 1 -f roary -e -n prokka/*.gff
```
The process was successfully done, but eventually the output folder was “roary_1512988994” while it should be "roary", making my following processes unable to find the outputs. This problem, however, didn’t happen when I used the command solely. How can I fix it?

**Comment by andrewjpage** [comment]
Your output logs should contain the following message:
"Output directory name exists already so adding a timestamp to the end"

Roary does not overwrite an existing directory.  The fix is to use a different name or modify your script to cleanup previous runs.

**Comment by thkuo** [comment]
In my case, the roary command in my Snakefile created two folders: roary and roary_1512999913. The final results (ie. core_gene_alignment.aln...etc) were only found in the roary_1512999913. As both the folders were created during the process, it was seemingly not resulted from the conflict of output name. 
The rule in my Snakefile is:
```
rule core_gene_alignment:
    input:
        "Snakefile"
    output:
        "{x}/core_gene_alignment.aln"
    threads: 30
    params:
        gff='prokka/*.gff'
    shell: "roary -p {threads} -f {wildcards.x} -e -n {params.gff}"
```

**Comment by andrewjpage** [comment]
I've double checked by running it manually and confirmed it works as I've described. Its likely a bug in your wrapper (I dont use snakemake so cant assist).

**Comment by htudela** [comment]
Hi snakemake fans,

I found an answer for this issue if anyone has the same problem. I am also using snakemake to call Roary. As snakemake automatically creates missing folders, it creates a folder based on the output, and Roary does to based on the directory option. So Roary uses a timestamp to identify the second folder. You will have to remove the directory created by snakemake in the rule before calling Roary in order to get rid of the timestamp thing. For instance :
`rm -r path/to/roary/folder
roary path/to/gff -f path/to/roary/folder`

I have tested it and it works !
