### ISSUE TITLE
MSG: Got a sequence without letters. Could not guess alphabet

### ISSUE THREAD

**Issue by allebiotech** [sanger-pathogens/Roary#410]
Hi, I've run Roary on 17 closely related strains but when I try to run the Roary script (pan_genome_core_alignment) to include an outgroup into the core alignment, a warning comes out:

MSG: Got a sequence without letters. Could not guess alphabet .

I've tried to add this:  -alphabet=>'dna' in the MergeMultifastaAlignments.pm but nothing changed (maybe I did it wrong? I'm not an expert user).

This issue was labelled as "bug" in 2016. Are there any new feedback?

My summary statistics file says:

Core genes  (99% <= strains <= 100%)  1759  
Soft core genes (95% <= strains < 99%)  0
Shell genes (15% <= strains < 95%)  2106
Cloud genes (0% <= strains < 15%)   3282
Total genes (0% <= strains <= 100%) 7147

Thanks in advance!

**Comment by andrewjpage** [comment]
Hi,
You need to include the outgroup along with the other files when you run
roary.
Andrew

**Comment by Guanguan8** [comment]
--------------------- WARNING ---------------------
MSG: Seq [GKOOBEJB_00026]: Terminator codon inside CDS!
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Seq [GKOOBEJB_00027]: Terminator codon inside CDS!
---------------------------------------------------
This happens when I comment it out, and  I try to run the Roary script ，a same warning comes out:

MSG: Got a sequence without letters. Could not guess alphabet .
 Are there any new feedback?

**Comment by Guanguan8** [comment]
-------------------- WARNING ---------------------
MSG: Seq [GKOOBEJB_00026]: Terminator codon inside CDS!
--------------------- WARNING ---------------------
MSG: Seq [GKOOBEJB_00027]: Terminator codon inside CDS!
This happens when I annotate genomes by prokka, and I try to run the Roary script ，a same warning comes out:

MSG: Got a sequence without letters. Could not guess alphabet .
Are there any new feedback?

**Comment by allebiotech** [comment]
Thanks a lot, it works! 👍

**Comment by andrewjpage** [comment]
@Guanguan8 Its an issue with Prokka: https://github.com/tseemann/prokka/issues/203

**Comment by Guanguan8** [comment]
@andrewjpage，
But  I'm looking at Mycoplasma's  which may use a different translation table，How to solve it？
Thanks in advance!

**Comment by vidhya123979** [comment]
@andrewjpage sir ,still i have issues for creating pan genome alignment file ,but gff files were correct but it showing 

![Screenshot from 2024-11-06 17-01-04](https://github.com/user-attachments/assets/dcb68fb6-6512-4379-9386-c61e5a4027b4)


2024/11/06 16:23:06 Running command: /home/dayholf/miniconda3/envs/pangenome/bin/FastTree -fastest -nt accessory_binary_genes.fa > accessory_binary_genes.fa.newick 
FastTree Version 2.1.11 Double precision (No SSE3)
Alignment: accessory_binary_genes.fa
Nucleotide distances: Jukes-Cantor Joins: balanced Support: SH-like 1000
Search: Fastest+2nd +NNI +SPR (2 rounds range 10) +ML-NNI opt-each=1
TopHits: 1.00*sqrtN close=default refresh=0.50
ML Model: Jukes-Cantor, CAT approximation with 20 rate categories
Initial topology in 0.02 seconds
Refining topology: 19 rounds ME-NNIs, 2 rounds ME-SPRs, 9 rounds ML-NNIs
Total branch-length 1.543 after 0.37 sec9, 1 of 24 splits   
ML-NNI round 1: LogLk = -10688.093 NNIs 2 max delta 2.05 Time 0.54
Switched to using 20 rate categories (CAT approximation)1 of 20   
Rate categories were divided by 0.693 so that average rate = 1.0
CAT-based log-likelihoods may not be comparable across runs
Use -gamma for approximate but comparable Gamma(20) log-likelihoods
ML-NNI round 2: LogLk = -10550.112 NNIs 1 max delta 0.00 Time 0.62
Turning off heuristics for final round of ML NNIs (converged)
ML-NNI round 3: LogLk = -10549.999 NNIs 0 max delta 0.00 Time 0.73 (final)
Optimize all lengths: LogLk = -10549.998 Time 0.76
Total time: 0.93 seconds Unique: 26/28 Bad splits: 0/23
Aligning each cluster
Use of uninitialized value in require at (eval 899) line 1.
2024/11/06 16:26:59 Running command: pan_genome_core_alignment -cd 99
2024/11/06 16:26:59 pan_genome_core_alignment -cd 99

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
---------------------------------------------------

--------------------- WARNING ---------------------
MSG: Got a sequence without letters. Could not guess alphabet
