### ISSUE TITLE
Interpretation accessory_binary_genes newick

### ISSUE THREAD

**Issue by MichWeb75** [sanger-pathogens/Roary#429]
Hi,
how to interpret the small distances in the newick tree, how are they calculated ? 
(A:0.053243069,B:0.061924073)
From gene_presence_absence.Rtab there are 1467 identical and 77 different groups for A and B.

**Comment by andrewjpage** [comment]
Hi,
More information on the tree here: http://sanger-pathogens.github.io/Roary/#accessory_binary_fasta
I wouldn't spend much time on looking at the numbers, its only a quick tree so that you can get a rough idea of whats in there (and so that you have a tree for visualisation tools). I usually take the core gene alignment and build a SNP tree with something like RAxML (and a bucket load of bootstraps) to get a tree for more indepth analysis.
